import ReactTest from "@/components/provider/Provider";
import "./globals.css";
import type { Metadata } from "next";
import { FONT_FAMILY } from "@/constants/global/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link href="https://cdn.jsdelivr.net/gh/source-foundry/Hack@3.003/web/hack.css" rel="stylesheet" />
      </head>
      <body className={FONT_FAMILY.gothic}>
        <ReactTest>{children}</ReactTest>
      </body>
    </html>
  );
}
