export const QUERY_KEYS = {
  KEYWORDLIST: "keywordList",
  POSTLIST: "postlist",
  POST: "post",
  COMMENTS: "comments",
  ALERTSETTING: "alertSetting",
  PARTICIPATEDLIST: "participatedList",
  LIVESEARCH: "liveSearch",
  DISCUSSIONLIST: "discussionList",
  ADDEDBYME: "addedByMe",
  ADDEDBYYOU: "addedByYou",
  ADDEDBYBOTH: "addedByBoth",
  BANNEDBYME: "bannedByMe",
  MYDISCUSSION: "myDiscussion",
  MYWRITTEN: "myWritten",
  DISCUSSION: "discussion",
  NEIGHBORPROFILE: "neighborProfile",
  NEIGHBORWRITTEN: "neighborWritten",
  NEIGHBORDISCUSSION: "neighborDiscussion",
  NEIGHBORKEYWORD: "neighborKeyword",
};
